export const countriesList = [
  { name: "Afghanistan", phone: "93", code: "AFG" },
  { name: "Albania", phone: "355", code: "ALB" },
  { name: "Algeria", phone: "213", code: "DZA" },
  { name: "American Samoa", phone: "1-684", code: "ASM" },
  { name: "Andorra", phone: "376", code: "AND" },
  { name: "Angola", phone: "244", code: "AGO" },
  { name: "Anguilla", phone: "1-264", code: "AIA" },
  { name: "Antarctica", phone: "672", code: "ATA" },
  { name: "Antigua and Barbuda", phone: "1-268", code: "ATG" },
  { name: "Argentina", phone: "54", code: "ARG" },
  { name: "Armenia", phone: "374", code: "ARM" },
  { name: "Aruba", phone: "297", code: "ABW" },
  { name: "Australia", phone: "61", code: "AUS" },
  { name: "Austria", phone: "43", code: "AUT" },
  { name: "Azerbaijan", phone: "994", code: "AZE" },
  { name: "Bahamas", phone: "1-242", code: "BHS" },
  { name: "Bahrain", phone: "973", code: "BHR" },
  { name: "Bangladesh", phone: "880", code: "BGD" },
  { name: "Barbados", phone: "1-246", code: "BRB" },
  { name: "Belarus", phone: "375", code: "BLR" },
  { name: "Belgium", phone: "32", code: "BEL" },
  { name: "Belize", phone: "501", code: "BLZ" },
  { name: "Benin", phone: "229", code: "BEN" },
  { name: "Bermuda", phone: "1-441", code: "BMU" },
  { name: "Bhutan", phone: "975", code: "BTN" },
  { name: "Bolivia", phone: "591", code: "BOL" },
  { name: "Bosnia and Herzegovina", phone: "387", code: "BIH" },
  { name: "Botswana", phone: "267", code: "BWA" },
  { name: "Brazil", phone: "55", code: "BRA" },
  { name: "British Indian Ocean Territory", phone: "246", code: "IOT" },
  { name: "British Virgin Islands", phone: "1-284", code: "VGB" },
  { name: "Brunei", phone: "673", code: "BRN" },
  { name: "Bulgaria", phone: "359", code: "BGR" },
  { name: "Burkina Faso", phone: "226", code: "BFA" },
  { name: "Burundi", phone: "257", code: "BDI" },
  { name: "Cambodia", phone: "855", code: "KHM" },
  { name: "Cameroon", phone: "237", code: "CMR" },
  { name: "Canada", phone: "1", code: "CAN" },
  { name: "Cape Verde", phone: "238", code: "CPV" },
  { name: "Cayman Islands", phone: "1-345", code: "CYM" },
  { name: "Central African Republic", phone: "236", code: "CAF" },
  { name: "Chad", phone: "235", code: "TCD" },
  { name: "Chile", phone: "56", code: "CHL" },
  { name: "China", phone: "86", code: "CHN" },
  { name: "Christmas Island", phone: "61", code: "CXR" },
  { name: "Cocos Islands", phone: "61", code: "CCK" },
  { name: "Colombia", phone: "57", code: "COL" },
  { name: "Comoros", phone: "269", code: "COM" },
  { name: "Cook Islands", phone: "682", code: "COK" },
  { name: "Costa Rica", phone: "506", code: "CRI" },
  { name: "Croatia", phone: "385", code: "HRV" },
  { name: "Cuba", phone: "53", code: "CUB" },
  { name: "Curacao", phone: "599", code: "CUW" },
  { name: "Cyprus", phone: "357", code: "CYP" },
  { name: "Czech Republic", phone: "420", code: "CZE" },
  { name: "Democratic Republic of the Congo", phone: "243", code: "COD" },
  { name: "Denmark", phone: "45", code: "DNK" },
  { name: "Djibouti", phone: "253", code: "DJI" },
  { name: "Dominica", phone: "1-767", code: "DMA" },
  { name: "Dominican Republic", phone: "1-809, 1-829, 1-849", code: "DOM" },
  { name: "East Timor", phone: "670", code: "TLS" },
  { name: "Ecuador", phone: "593", code: "ECU" },
  { name: "Egypt", phone: "20", code: "EGY" },
  { name: "El Salvador", phone: "503", code: "SLV" },
  { name: "Equatorial Guinea", phone: "240", code: "GNQ" },
  { name: "Eritrea", phone: "291", code: "ERI" },
  { name: "Estonia", phone: "372", code: "EST" },
  { name: "Ethiopia", phone: "251", code: "ETH" },
  { name: "Falkland Islands", phone: "500", code: "FLK" },
  { name: "Faroe Islands", phone: "298", code: "FRO" },
  { name: "Fiji", phone: "679", code: "FJI" },
  { name: "Finland", phone: "358", code: "FIN" },
  { name: "France", phone: "33", code: "FRA" },
  { name: "French Polynesia", phone: "689", code: "PYF" },
  { name: "Gabon", phone: "241", code: "GAB" },
  { name: "Gambia", phone: "220", code: "GMB" },
  { name: "Georgia", phone: "995", code: "GEO" },
  { name: "Germany", phone: "49", code: "DEU" },
  { name: "Ghana", phone: "233", code: "GHA" },
  { name: "Gibraltar", phone: "350", code: "GIB" },
  { name: "Greece", phone: "30", code: "GRC" },
  { name: "Greenland", phone: "299", code: "GRL" },
  { name: "Grenada", phone: "1-473", code: "GRD" },
  { name: "Guam", phone: "1-671", code: "GUM" },
  { name: "Guatemala", phone: "502", code: "GTM" },
  { name: "Guernsey", phone: "44-1481", code: "GGY" },
  { name: "Guinea", phone: "224", code: "GIN" },
  { name: "Guinea-Bissau", phone: "245", code: "GNB" },
  { name: "Guyana", phone: "592", code: "GUY" },
  { name: "Haiti", phone: "509", code: "HTI" },
  { name: "Honduras", phone: "504", code: "HND" },
  { name: "Hong Kong", phone: "852", code: "HKG" },
  { name: "Hungary", phone: "36", code: "HUN" },
  { name: "Iceland", phone: "354", code: "ISL" },
  { name: "India", phone: "91", code: "IND" },
  { name: "Indonesia", phone: "62", code: "IDN" },
  { name: "Iran", phone: "98", code: "IRN" },
  { name: "Iraq", phone: "964", code: "IRQ" },
  { name: "Ireland", phone: "353", code: "IRL" },
  { name: "Isle of Man", phone: "44-1624", code: "IMN" },
  { name: "Israel", phone: "972", code: "ISR" },
  { name: "Italy", phone: "39", code: "ITA" },
  { name: "Ivory Coast", phone: "225", code: "CIV" },
  { name: "Jamaica", phone: "1-876", code: "JAM" },
  { name: "Japan", phone: "81", code: "JPN" },
  { name: "Jersey", phone: "44-1534", code: "JEY" },
  { name: "Jordan", phone: "962", code: "JOR" },
  { name: "Kazakhstan", phone: "7", code: "KAZ" },
  { name: "Kenya", phone: "254", code: "KEN" },
  { name: "Kiribati", phone: "686", code: "KIR" },
  { name: "Kosovo", phone: "383", code: "XKX" },
  { name: "Kuwait", phone: "965", code: "KWT" },
  { name: "Kyrgyzstan", phone: "996", code: "KGZ" },
  { name: "Laos", phone: "856", code: "LAO" },
  { name: "Latvia", phone: "371", code: "LVA" },
  { name: "Lebanon", phone: "961", code: "LBN" },
  { name: "Lesotho", phone: "266", code: "LSO" },
  { name: "Liberia", phone: "231", code: "LBR" },
  { name: "Libya", phone: "218", code: "LBY" },
  { name: "Liechtenstein", phone: "423", code: "LIE" },
  { name: "Lithuania", phone: "370", code: "LTU" },
  { name: "Luxembourg", phone: "352", code: "LUX" },
  { name: "Macau", phone: "853", code: "MAC" },
  { name: "Macedonia", phone: "389", code: "MKD" },
  { name: "Madagascar", phone: "261", code: "MDG" },
  { name: "Malawi", phone: "265", code: "MWI" },
  { name: "Malaysia", phone: "60", code: "MYS" },
  { name: "Maldives", phone: "960", code: "MDV" },
  { name: "Mali", phone: "223", code: "MLI" },
  { name: "Malta", phone: "356", code: "MLT" },
  { name: "Marshall Islands", phone: "692", code: "MHL" },
  { name: "Mauritania", phone: "222", code: "MRT" },
  { name: "Mauritius", phone: "230", code: "MUS" },
  { name: "Mayotte", phone: "262", code: "MYT" },
  { name: "Mexico", phone: "52", code: "MEX" },
  { name: "Micronesia", phone: "691", code: "FSM" },
  { name: "Moldova", phone: "373", code: "MDA" },
  { name: "Monaco", phone: "377", code: "MCO" },
  { name: "Mongolia", phone: "976", code: "MNG" },
  { name: "Montenegro", phone: "382", code: "MNE" },
  { name: "Montserrat", phone: "1-664", code: "MSR" },
  { name: "Morocco", phone: "212", code: "MAR" },
  { name: "Mozambique", phone: "258", code: "MOZ" },
  { name: "Myanmar", phone: "95", code: "MMR" },
  { name: "Namibia", phone: "264", code: "NAM" },
  { name: "Nauru", phone: "674", code: "NRU" },
  { name: "Nepal", phone: "977", code: "NPL" },
  { name: "Netherlands", phone: "31", code: "NLD" },
  { name: "Netherlands Antilles", phone: "599", code: "ANT" },
  { name: "New Caledonia", phone: "687", code: "NCL" },
  { name: "New Zealand", phone: "64", code: "NZL" },
  { name: "Nicaragua", phone: "505", code: "NIC" },
  { name: "Niger", phone: "227", code: "NER" },
  { name: "Nigeria", phone: "234", code: "NGA" },
  { name: "Niue", phone: "683", code: "NIU" },
  { name: "North Korea", phone: "850", code: "PRK" },
  { name: "Northern Mariana Islands", phone: "1-670", code: "MNP" },
  { name: "Norway", phone: "47", code: "NOR" },
  { name: "Oman", phone: "968", code: "OMN" },
  { name: "Pakistan", phone: "92", code: "PAK" },
  { name: "Palau", phone: "680", code: "PLW" },
  { name: "Palestine", phone: "970", code: "PSE" },
  { name: "Panama", phone: "507", code: "PAN" },
  { name: "Papua New Guinea", phone: "675", code: "PNG" },
  { name: "Paraguay", phone: "595", code: "PRY" },
  { name: "Peru", phone: "51", code: "PER" },
  { name: "Philippines", phone: "63", code: "PHL" },
  { name: "Pitcairn", phone: "64", code: "PCN" },
  { name: "Poland", phone: "48", code: "POL" },
  { name: "Portugal", phone: "351", code: "PRT" },
  { name: "Puerto Rico", phone: "1-787, 1-939", code: "PRI" },
  { name: "Qatar", phone: "974", code: "QAT" },
  { name: "Republic of the Congo", phone: "242", code: "COG" },
  { name: "Reunion", phone: "262", code: "REU" },
  { name: "Romania", phone: "40", code: "ROU" },
  { name: "Russia", phone: "7", code: "RUS" },
  { name: "Rwanda", phone: "250", code: "RWA" },
  { name: "Saint Barthelemy", phone: "590", code: "BLM" },
  { name: "Saint Helena", phone: "290", code: "SHN" },
  { name: "Saint Kitts and Nevis", phone: "1-869", code: "KNA" },
  { name: "Saint Lucia", phone: "1-758", code: "LCA" },
  { name: "Saint Martin", phone: "590", code: "MAF" },
  { name: "Saint Pierre and Miquelon", phone: "508", code: "SPM" },
  { name: "Saint Vincent and the Grenadines", phone: "1-784", code: "VCT" },
  { name: "Samoa", phone: "685", code: "WSM" },
  { name: "San Marino", phone: "378", code: "SMR" },
  { name: "Sao Tome and Principe", phone: "239", code: "STP" },
  { name: "Saudi Arabia", phone: "966", code: "SAU" },
  { name: "Senegal", phone: "221", code: "SEN" },
  { name: "Serbia", phone: "381", code: "SRB" },
  { name: "Seychelles", phone: "248", code: "SYC" },
  { name: "Sierra Leone", phone: "232", code: "SLE" },
  { name: "Singapore", phone: "65", code: "SGP" },
  { name: "Sint Maarten", phone: "1-721", code: "SXM" },
  { name: "Slovakia", phone: "421", code: "SVK" },
  { name: "Slovenia", phone: "386", code: "SVN" },
  { name: "Solomon Islands", phone: "677", code: "SLB" },
  { name: "Somalia", phone: "252", code: "SOM" },
  { name: "South Africa", phone: "27", code: "ZAF" },
  { name: "South Korea", phone: "82", code: "KOR" },
  { name: "South Sudan", phone: "211", code: "SSD" },
  { name: "Spain", phone: "34", code: "ESP" },
  { name: "Sri Lanka", phone: "94", code: "LKA" },
  { name: "Sudan", phone: "249", code: "SDN" },
  { name: "Suriname", phone: "597", code: "SUR" },
  { name: "Svalbard and Jan Mayen", phone: "47", code: "SJM" },
  { name: "Swaziland", phone: "268", code: "SWZ" },
  { name: "Sweden", phone: "46", code: "SWE" },
  { name: "Switzerland", phone: "41", code: "CHE" },
  { name: "Syria", phone: "963", code: "SYR" },
  { name: "Taiwan", phone: "886", code: "TWN" },
  { name: "Tajikistan", phone: "992", code: "TJK" },
  { name: "Tanzania", phone: "255", code: "TZA" },
  { name: "Thailand", phone: "66", code: "THA" },
  { name: "Togo", phone: "228", code: "TGO" },
  { name: "Tokelau", phone: "690", code: "TKL" },
  { name: "Tonga", phone: "676", code: "TON" },
  { name: "Trinidad and Tobago", phone: "1-868", code: "TTO" },
  { name: "Tunisia", phone: "216", code: "TUN" },
  { name: "Turkey", phone: "90", code: "TUR" },
  { name: "Turkmenistan", phone: "993", code: "TKM" },
  { name: "Turks and Caicos Islands", phone: "1-649", code: "TCA" },
  { name: "Tuvalu", phone: "688", code: "TUV" },
  { name: "U.S. Virgin Islands", phone: "1-340", code: "VIR" },
  { name: "Uganda", phone: "256", code: "UGA" },
  { name: "Ukraine", phone: "380", code: "UKR" },
  { name: "United Arab Emirates", phone: "971", code: "ARE" },
  { name: "United Kingdom", phone: "44", code: "GBR" },
  { name: "United States", phone: "1", code: "USA" },
  { name: "Uruguay", phone: "598", code: "URY" },
  { name: "Uzbekistan", phone: "998", code: "UZB" },
  { name: "Vanuatu", phone: "678", code: "VUT" },
  { name: "Vatican", phone: "379", code: "VAT" },
  { name: "Venezuela", phone: "58", code: "VEN" },
  { name: "Vietnam", phone: "84", code: "VNM" },
  { name: "Wallis and Futuna", phone: "681", code: "WLF" },
  { name: "Western Sahara", phone: "212", code: "ESH" },
  { name: "Yemen", phone: "967", code: "YEM" },
  { name: "Zambia", phone: "260", code: "ZMB" },
  { name: "Zimbabwe", phone: "263", code: "ZWE" },
];
