export const myProfileConfig = {
  formValid: false,
  fields: [
    {
      type: "TEXTBOX",
      controlId: "email",
      label: "Enter Email Address",
      placeholder: "Enter Email Address",
      controlType: "email",
      size: "lg",
      rules: [
        { id: "REQUIRED", message: "Email is Required" },
        { id: "EMAIL", message: "Value is not valid" },
      ],
      valid: false,
      showValidationMessage: true,
      validationMessages: ["Email is Required", "Value is not valid"],
    },
    {
      type: "TEXTBOX",
      controlId: "firstName",
      label: "Enter First Name",
      placeholder: "Enter First Name",
      controlType: "text",
      size: "lg",
      rules: [{ id: "REQUIRED", message: "First Name is Required" }],
      valid: false,
      showValidationMessage: true,
      validationMessages: ["First Name is Required"],
    },
    {
      type: "TEXTBOX",
      controlId: "lastName",
      label: "Enter Last Name",
      placeholder: "Enter Last Name",
      controlType: "text",
      size: "lg",
      rules: [{ id: "REQUIRED", message: "Last Name is Required" }],
      valid: false,
      showValidationMessage: true,
      validationMessages: ["Last Name is Required"],
    },
    {
      type: "TEXTBOX",
      controlId: "city",
      label: "Enter City Name",
      placeholder: "Enter City Name",
      controlType: "text",
      size: "lg",
      rules: [{ id: "REQUIRED", message: "City Name is Required" }],
      valid: false,
      showValidationMessage: true,
      validationMessages: ["City Name is Required"],
    },
    {
      type: "TEXTBOX",
      controlId: "state",
      label: "Enter State Name",
      placeholder: "Enter State Name",
      controlType: "text",
      size: "lg",
      rules: [{ id: "REQUIRED", message: "State Name is Required" }],
      valid: false,
      showValidationMessage: true,
      validationMessages: ["State Name is Required"],
    },
    {
      type: "TEXTBOX",
      controlId: "country",
      label: "Enter Country Name",
      placeholder: "Enter Country Name",
      controlType: "text",
      size: "lg",
      rules: [{ id: "REQUIRED", message: "Country Name is Required" }],
      valid: false,
      showValidationMessage: true,
      validationMessages: ["Country Name is Required"],
    },
    {
      type: "TEXTBOX",
      controlId: "phone",
      label: "Enter Phone Number",
      placeholder: "Enter Phone Number",
      controlType: "text",
      size: "lg",
      rules: [{ id: "REQUIRED", message: "Phone Number is Required" }],
      valid: false,
      showValidationMessage: true,
      validationMessages: ["Phone Number is Required"],
    },
  ],
};
