export const loginFormConfig = {
  formValid: false,
  fields: [
    {
      type: "TEXTBOX",
      controlId: "formPropName",
      label: "Enter Property Name",
      placeholder: "Enter Property Name",
      controlType: "text",
      size: "lg",
      rules: [{ id: "REQUIRED", message: "Name is Required" }],
      valid: false,
      showValidationMessage: true,
      validationMessages: ["Name is Required"],
    },
    {
      type: "TEXTBOX",
      controlId: "formPropAddress1",
      label: "Enter Property Address1",
      placeholder: "Enter Property Address1",
      controlType: "text",
      size: "lg",
      rules: [{ id: "REQUIRED", message: "Address1 is Required" }],
      valid: false,
      showValidationMessage: true,
      validationMessages: ["Address1 is Required"],
    },
    {
      type: "TEXTBOX",
      controlId: "formPropAddress2",
      label: "Enter Property Address2",
      placeholder: "Enter Property Address2",
      controlType: "text",
      size: "lg",
      rules: [{ id: "REQUIRED", message: "Address2 is Required" }],
      valid: false,
      showValidationMessage: true,
      validationMessages: ["Address2 is Required"],
    },
    {
      type: "TEXTBOX",
      controlId: "formPropCity",
      label: "Enter Property City",
      placeholder: "Enter Property City",
      controlType: "text",
      size: "lg",
      rules: [{ id: "REQUIRED", message: "City is Required" }],
      valid: false,
      showValidationMessage: true,
      validationMessages: ["City is Required"],
    },
    {
      type: "TEXTBOX",
      controlId: "formPropCountry",
      label: "Enter Property Country",
      placeholder: "Enter Property Country",
      controlType: "text",
      size: "lg",
      rules: [{ id: "REQUIRED", message: "Country is Required" }],
      valid: false,
      showValidationMessage: true,
      validationMessages: ["Country is Required"],
    },
    {
      type: "TEXTBOX",
      controlId: "formPropZip",
      label: "Enter Property Zip",
      placeholder: "Enter Property Zip",
      controlType: "text",
      size: "lg",
      rules: [{ id: "REQUIRED", message: "Zip is Required" }],
      valid: false,
      showValidationMessage: true,
      validationMessages: ["Zip is Required"],
    },
    {
      type: "TEXTBOX",
      controlId: "formPropLandmark",
      label: "Enter Property Landmark",
      placeholder: "Enter Property Landmark",
      controlType: "text",
      size: "lg",
      rules: [{ id: "REQUIRED", message: "Landmark is Required" }],
      valid: false,
      showValidationMessage: true,
      validationMessages: ["Landmark is Required"],
    },
    {
      type: "TEXTBOX",
      controlId: "formPropArea(sq. ft.)",
      label: "Enter Property Area(sq. ft.)",
      placeholder: "Enter Property Area(sq. ft.)",
      controlType: "text",
      size: "lg",
      rules: [{ id: "REQUIRED", message: "Area(sq. ft.) is Required" }],
      valid: false,
      showValidationMessage: true,
      validationMessages: ["Area(sq. ft.) is Required"],
    },
    {
      type: "TEXTBOX",
      controlId: "formPropValue",
      label: "Enter Property Value",
      placeholder: "Enter Property Value",
      controlType: "text",
      size: "lg",
      rules: [{ id: "REQUIRED", message: "Value is Required" }],
      valid: false,
      showValidationMessage: true,
      validationMessages: ["Value is Required"],
    },
    {
      type: "TEXTBOX",
      controlId: "formPropAbout",
      label: "Enter Property About",
      placeholder: "Enter Property About",
      controlType: "text",
      size: "lg",
      rules: [{ id: "REQUIRED", message: "About is Required" }],
      valid: false,
      showValidationMessage: true,
      validationMessages: ["About is Required"],
    },
    {
      type: "TEXTBOX",
      controlId: "formPropMap Link",
      label: "Enter Property Map Link",
      placeholder: "Enter Property Map Link",
      controlType: "text",
      size: "lg",
      rules: [{ id: "REQUIRED", message: "Map Link is Required" }],
      valid: false,
      showValidationMessage: true,
      validationMessages: ["Map Link is Required"],
    },
    {
      type: "TEXTBOX",
      controlId: "formPropBedrooms",
      label: "Enter Property Bedrooms",
      placeholder: "Enter Property Bedrooms",
      controlType: "text",
      size: "lg",
      rules: [{ id: "REQUIRED", message: "Bedrooms is Required" }],
      valid: false,
      showValidationMessage: true,
      validationMessages: ["Bedrooms is Required"],
    },
    {
      type: "TEXTBOX",
      controlId: "formPropBathroom",
      label: "Enter Property Bathroom",
      placeholder: "Enter Property Bathroom",
      controlType: "text",
      size: "lg",
      rules: [{ id: "REQUIRED", message: "Bathroom is Required" }],
      valid: false,
      showValidationMessage: true,
      validationMessages: ["Bathroom is Required"],
    },
  ],
};
