export const loginFormConfig = {
  formValid: false,
  fields: [
    {
      type: "TEXTBOX",
      controlId: "formBasicEmail",
      label: "Enter Email Address",
      placeholder: "Enter Email Address",
      controlType: "email",
      size: "lg",
      rules: [
        { id: "REQUIRED", message: "Email is Required" },
        { id: "EMAIL", message: "Value is not valid" },
      ],
      valid: false,
      showValidationMessage: true,
      validationMessages: ["Email is Required", "Value is not valid"],
    },
    {
      type: "TEXTBOX",
      controlId: "formBasicPassword",
      label: "Enter Password",
      placeholder: "Enter Password",
      controlType: "password",
      size: "lg",
      rules: [{ id: "REQUIRED", message: "Password is Required" }],
      valid: false,
      showValidationMessage: true,
      validationMessages: ["Password is Required"],
    },
  ],
};

export const signupFormConfig = {
  formValid: false,
  fields: [
    {
      type: "TEXTBOX",
      controlId: "formBasicFullName",
      label: "Enter Full Name",
      placeholder: "Enter Full Name",
      controlType: "text",
      size: "lg",
      rules: [{ id: "REQUIRED", message: "Email is Required" }],
      valid: false,
      showValidationMessage: true,
      validationMessages: ["Full Name is Required"],
    },
    {
      type: "TEXTBOX",
      controlId: "formBasicAddress",
      label: "Enter Address",
      placeholder: "Enter Address",
      controlType: "text",
      size: "lg",
      rules: [{ id: "REQUIRED", message: "Address is Required" }],
      valid: false,
      showValidationMessage: true,
      validationMessages: ["Address is Required"],
    },
    {
      type: "TEXTBOX",
      controlId: "formBasicEmail",
      label: "Enter Email Address",
      placeholder: "Enter Email Address",
      controlType: "email",
      size: "lg",
      rules: [
        { id: "REQUIRED", message: "Email is Required" },
        { id: "EMAIL", message: "Value is not valid" },
      ],
      valid: false,
      showValidationMessage: true,
      validationMessages: ["Email is Required", "Value is not valid"],
    },
    {
      type: "TEXTBOX",
      controlId: "formBasicPassword",
      label: "Enter Password",
      placeholder: "Enter Password",
      controlType: "password",
      size: "lg",
      rules: [{ id: "REQUIRED", message: "Password is Required" }],
      valid: false,
      showValidationMessage: true,
      validationMessages: ["Password is Required"],
    },
  ],
};
